version: '3'
services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    ports:
      - "3307:3306"
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/my.cnf
      - master-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - replication

  slave:
    image: mysql:8.0
    container_name: mysql-slave
    ports:
      - "3308:3306"
    volumes:
      - ./slave.cnf:/etc/mysql/conf.d/my.cnf
      - slave-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - replication
    depends_on:
      - master

networks:
  replication:

volumes:
  master-data:
  slave-data: